Rigid Body Dynamics Library: Contacts
Contacts
Data Structures
struct ConstraintSet
Structure that contains both constraint information and workspace memory.
Functions
RBDL_DLLAPI void CalcContactJacobian (Model &model, const Math::VectorNd &Q, const ConstraintSet &CS, Math::MatrixNd &G, bool update_kinematics=true)
Computes the Jacobian for the given ConstraintSet.
RBDL_DLLAPI void CalcContactSystemVariables (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, const Math::VectorNd &Tau, ConstraintSet &CS)
RBDL_DLLAPI void ForwardDynamicsContactsDirect (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, const Math::VectorNd &Tau, ConstraintSet &CS, Math::VectorNd &QDDot)
Computes forward dynamics with contact by constructing and solving the full lagrangian equation.
RBDL_DLLAPI void ForwardDynamicsContactsRangeSpaceSparse (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, const Math::VectorNd &Tau, ConstraintSet &CS, Math::VectorNd &QDDot)
RBDL_DLLAPI void ForwardDynamicsContactsNullSpace (Model &model, const VectorNd &Q, const VectorNd &QDot, const VectorNd &Tau, ConstraintSet &CS, VectorNd &QDDot)
RBDL_DLLAPI void ForwardDynamicsContactsKokkevis (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, const Math::VectorNd &Tau, ConstraintSet &CS, Math::VectorNd &QDDot)
Computes forward dynamics that accounts for active contacts in ConstraintSet.
RBDL_DLLAPI void ComputeContactImpulsesDirect (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDotMinus, ConstraintSet &CS, Math::VectorNd &QDotPlus)
Computes contact gain by constructing and solving the full lagrangian equation.
RBDL_DLLAPI void ComputeContactImpulsesRangeSpaceSparse (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDotMinus, ConstraintSet &CS, Math::VectorNd &QDotPlus)
Resolves contact gain using SolveContactSystemRangeSpaceSparse()
RBDL_DLLAPI void ComputeContactImpulsesNullSpace (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDotMinus, ConstraintSet &CS, Math::VectorNd &QDotPlus)
Resolves contact gain using SolveContactSystemNullSpace()
RBDL_DLLAPI void SolveContactSystemDirect (Math::MatrixNd &H, const Math::MatrixNd &G, const Math::VectorNd &c, const Math::VectorNd &gamma, Math::VectorNd &qddot, Math::VectorNd &lambda, Math::MatrixNd &A, Math::VectorNd &b, Math::VectorNd &x, Math::LinearSolver &linear_solver)
Solves the full contact system directly, i.e. simultaneously for contact forces and joint accelerations.
RBDL_DLLAPI void SolveContactSystemRangeSpaceSparse (Model &model, Math::MatrixNd &H, const Math::MatrixNd &G, const Math::VectorNd &c, const Math::VectorNd &gamma, Math::VectorNd &qddot, Math::VectorNd &lambda, Math::MatrixNd &K, Math::VectorNd &a, Math::LinearSolver linear_solver)
Solves the contact system by first solving for the the joint accelerations and then the contact forces using a sparse matrix decomposition of the joint space inertia matrix.
RBDL_DLLAPI void SolveContactSystemNullSpace (Math::MatrixNd &H, const Math::MatrixNd &G, const Math::VectorNd &c, const Math::VectorNd &gamma, Math::VectorNd &qddot, Math::VectorNd &lambda, Math::MatrixNd &Y, Math::MatrixNd &Z, Math::VectorNd &qddot_y, Math::VectorNd &qddot_z, Math::LinearSolver &linear_solver)
Solves the contact system by first solving for the joint accelerations and then for the constraint forces.
Detailed Description
External contacts are handled by specification of a ConstraintSet which contains all informations about the current contacts and workspace memory.
Separate contacts can be specified by calling ConstraintSet::AddConstraint(). After all constraints have been specified, this ConstraintSet has to be bound to the model via ConstraintSet::Bind(). This initializes workspace memory that is later used when calling one of the contact functions, such as ForwardDynamicsContacts() or ForwardDynamicsContactsLagrangian().
The values in the vectors ConstraintSet::force and ConstraintSet::impulse contain the computed force or impulse values for each constraint when returning from one of the contact functions.
Solution of the Constraint System
Linear System of the Constrained Dynamics
External contacts are constraints that act on the model. To compute the acceleration one has to solve a linear system of the form:
where is the joint space inertia matrix computed with the CompositeRigidBodyAlgorithm(), are the point jacobians of the contact points, the bias force (sometimes called "non-linear effects"), and the generalized acceleration independent part of the contact point accelerations.
Linear System of the Contact Collision
Similarly to compute the response of the model to a contact gain one has to solve a system of the following form:
where is the joint space inertia matrix computed with the CompositeRigidBodyAlgorithm(), are the point jacobians of the contact points, the generalized velocity after the impact, the impulses at each constraint, the generalized velocity before the impact, and the desired velocity of each constraint after the impact (known beforehand, usually 0). The value of can is specified via the variable ConstraintSet::v_plus and defaults to 0.
Solution Methods
There are essentially three different approaches to solve these systems:
Direct: solve the full system to simultaneously compute and . This may be slow for large systems and many constraints.
Range-Space: solve first for and then for .
Null-Space: solve furst for and then for The methods are the same for the contact gaints just with different variables on the right-hand-side.
RBDL provides methods for all approaches. The implementation for the range-space method also exploits sparsities in the joint space inertia matrix using a sparse structure preserving decomposition as described in Chapter 8.5 of "Rigid Body Dynamics Algorithms".
None of the methods is generally superior to the others and each has different trade-offs as factors such as model topology, number of constraints, constrained bodies, numerical stability, and performance vary and evaluation has to be made on a case-by-case basis.
Methods for Solving Constrained Dynamics
RBDL provides the following methods to compute the acceleration of a constrained system:
ForwardDynamicsContactsDirect()
ForwardDynamicsContactsRangeSpaceSparse()
ForwardDynamicsContactsNullSpace()
Methods for Computing Collisions
RBDL provides the following methods to compute the collision response on new contact gains:
ComputeContactImpulsesDirect()
ComputeContactImpulsesRangeSpaceSparse()
ComputeContactImpulsesNullSpace()
Function Documentation
RBDL_DLLAPI void CalcContactJacobian (Model & model, const Math::VectorNd & Q, const ConstraintSet & CS, Math::MatrixNd & G, bool update_kinematics = true)
Computes the Jacobian for the given ConstraintSet.
Parameters
model the model
Q the generalized positions of the joints
CS the constraint set for which the Jacobian should be computed
G (output) matrix where the output will be stored in
update_kinematics whether the kinematics of the model should be * updated from Q
Definition at line 309 of file Contacts.cc.
References ConstraintSet::body, RigidBodyDynamics::CalcPointJacobian(), Model::dof_count, ConstraintSet::normal, ConstraintSet::point, ConstraintSet::size(), and RigidBodyDynamics::UpdateKinematicsCustom().
RBDL_DLLAPI void CalcContactSystemVariables (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, const Math::VectorNd & Tau, ConstraintSet & CS)
Definition at line 343 of file Contacts.cc.
References ConstraintSet::acceleration, ConstraintSet::body, ConstraintSet::C, RigidBodyDynamics::CalcContactJacobian(), RigidBodyDynamics::CalcPointAcceleration(), RigidBodyDynamics::CompositeRigidBodyAlgorithm(), Model::dof_count, ConstraintSet::G, ConstraintSet::gamma, ConstraintSet::H, Model::lambda, Model::mBodies, RigidBodyDynamics::NonlinearEffects(), ConstraintSet::normal, ConstraintSet::point, ConstraintSet::QDDot_0, ConstraintSet::size(), RigidBodyDynamics::UpdateKinematicsCustom(), Model::X_base, and Model::X_lambda.
RBDL_DLLAPI void ComputeContactImpulsesDirect (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDotMinus, ConstraintSet & CS, Math::VectorNd & QDotPlus)
Computes contact gain by constructing and solving the full lagrangian equation.
This method builds and solves the linear system
where is the joint space inertia matrix computed with the CompositeRigidBodyAlgorithm(), are the point jacobians of the contact points, the generalized velocity after the impact, the impulses at each constraint, the generalized velocity before the impact, and the desired velocity of each constraint after the impact (known beforehand, usually 0). The value of can is specified via the variable ConstraintSet::v_plus and defaults to 0.
Note
So far, only constraints acting along cartesian coordinate axes are allowed (i.e. (1, 0, 0), (0, 1, 0), and (0, 0, 1)). Also, one must not specify redundant constraints!
Note
To increase performance group constraints body and pointwise such that constraints acting on the same body point are sequentially in ConstraintSet. This can save computation of point Jacobians .
Parameters
model rigid body model
Q state vector of the internal joints
QDotMinus velocity vector of the internal joints before the impact
CS the set of active constraints
QDotPlus velocities of the internals joints after the impact (output)
Definition at line 454 of file Contacts.cc.
References ConstraintSet::A, ConstraintSet::b, RigidBodyDynamics::CalcContactJacobian(), RigidBodyDynamics::CompositeRigidBodyAlgorithm(), Model::dof_count, ConstraintSet::G, ConstraintSet::H, ConstraintSet::impulse, ConstraintSet::linear_solver, ConstraintSet::size(), RigidBodyDynamics::SolveContactSystemDirect(), RigidBodyDynamics::UpdateKinematicsCustom(), ConstraintSet::v_plus, and ConstraintSet::x.
RBDL_DLLAPI void ComputeContactImpulsesNullSpace (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDotMinus, ConstraintSet & CS, Math::VectorNd & QDotPlus)
Resolves contact gain using SolveContactSystemNullSpace()
Definition at line 499 of file Contacts.cc.
References RigidBodyDynamics::CalcContactJacobian(), RigidBodyDynamics::CompositeRigidBodyAlgorithm(), ConstraintSet::G, ConstraintSet::GT_qr, ConstraintSet::GT_qr_Q, ConstraintSet::H, ConstraintSet::impulse, ConstraintSet::linear_solver, ConstraintSet::qddot_y, ConstraintSet::qddot_z, RigidBodyDynamics::SolveContactSystemNullSpace(), RigidBodyDynamics::UpdateKinematicsCustom(), ConstraintSet::v_plus, ConstraintSet::Y, and ConstraintSet::Z.
RBDL_DLLAPI void ComputeContactImpulsesRangeSpaceSparse (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDotMinus, ConstraintSet & CS, Math::VectorNd & QDotPlus)
Resolves contact gain using SolveContactSystemRangeSpaceSparse()
Definition at line 481 of file Contacts.cc.
References ConstraintSet::a, RigidBodyDynamics::CalcContactJacobian(), RigidBodyDynamics::CompositeRigidBodyAlgorithm(), ConstraintSet::G, ConstraintSet::H, ConstraintSet::impulse, ConstraintSet::K, ConstraintSet::linear_solver, RigidBodyDynamics::SolveContactSystemRangeSpaceSparse(), RigidBodyDynamics::UpdateKinematicsCustom(), and ConstraintSet::v_plus.
RBDL_DLLAPI void ForwardDynamicsContactsDirect (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, const Math::VectorNd & Tau, ConstraintSet & CS, Math::VectorNd & QDDot)
Computes forward dynamics with contact by constructing and solving the full lagrangian equation.
This method builds and solves the linear system
where is the joint space inertia matrix computed with the CompositeRigidBodyAlgorithm(), are the point jacobians of the contact points, the bias force (sometimes called "non-linear effects"), and the generalized acceleration independent part of the contact point accelerations.
Note
So far, only constraints acting along cartesian coordinate axes are allowed (i.e. (1, 0, 0), (0, 1, 0), and (0, 0, 1)). Also, one must not specify redundant constraints!
Note
To increase performance group constraints body and pointwise such that constraints acting on the same body point are sequentially in ConstraintSet. This can save computation of point jacobians .
Parameters
model rigid body model
Q state vector of the internal joints
QDot velocity vector of the internal joints
Tau actuations of the internal joints
CS the description of all acting constraints
QDDot accelerations of the internals joints (output)
Note
During execution of this function values such as ConstraintSet::force get modified and will contain the value of the force acting along the normal.
Definition at line 388 of file Contacts.cc.
References ConstraintSet::A, ConstraintSet::b, ConstraintSet::C, RigidBodyDynamics::CalcContactSystemVariables(), Model::dof_count, ConstraintSet::force, ConstraintSet::G, ConstraintSet::gamma, ConstraintSet::H, ConstraintSet::linear_solver, LOG, ConstraintSet::size(), RigidBodyDynamics::SolveContactSystemDirect(), and ConstraintSet::x.
RBDL_DLLAPI void ForwardDynamicsContactsKokkevis (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, const Math::VectorNd & Tau, ConstraintSet & CS, Math::VectorNd & QDDot)
Computes forward dynamics that accounts for active contacts in ConstraintSet.
The method used here is the one described by Kokkevis and Metaxas in the Paper "Practical Physics for Articulated Characters", Game Developers Conference, 2004.
It does this by recursively computing the inverse articulated-body inertia (IABI)
which is then used to build and solve a system of the form: Here is the number of constraints and the method for building the system uses the Articulated Body Algorithm to efficiently compute entries of the system. The values are the constraint accelerations, the constraint forces, and are the constraint bias forces.
Parameters
model rigid body model
Q state vector of the internal joints
QDot velocity vector of the internal joints
Tau actuations of the internal joints
CS a list of all contact points
QDDot accelerations of the internals joints (output)
Note
During execution of this function values such as ConstraintSet::force get modified and will contain the value of the force acting along the normal.
Todo:
Allow for external forces
Definition at line 836 of file Contacts.cc.
References ConstraintSet::a, ConstraintSet::acceleration, SpatialTransform::applyAdjoint(), ConstraintSet::body, RigidBodyDynamics::CalcBodyToBaseCoordinates(), RigidBodyDynamics::CalcPointAcceleration(), Model::dof_count, ConstraintSet::f_ext_constraints, ConstraintSet::f_t, Model::fixed_body_discriminator, ConstraintSet::force, RigidBodyDynamics::ForwardDynamics(), RigidBodyDynamics::ForwardDynamicsAccelerationDeltas(), RigidBodyDynamics::ForwardDynamicsApplyConstraintForces(), Model::IsFixedBodyId(), ConstraintSet::K, ConstraintSet::linear_solver, LinearSolverColPivHouseholderQR, LinearSolverHouseholderQR, LinearSolverPartialPivLU, RigidBodyDynamics::Math::LinSolveGaussElimPivot(), LOG, Model::mBodies, Model::mFixedBodies, ConstraintSet::normal, ConstraintSet::point, ConstraintSet::point_accel_0, ConstraintSet::QDDot_0, ConstraintSet::QDDot_t, ConstraintSet::size(), SUPPRESS_LOGGING, and RigidBodyDynamics::UpdateKinematicsCustom().
RBDL_DLLAPI void ForwardDynamicsContactsNullSpace (Model & model, const VectorNd & Q, const VectorNd & QDot, const VectorNd & Tau, ConstraintSet & CS, VectorNd & QDDot)
Definition at line 428 of file Contacts.cc.
References ConstraintSet::C, RigidBodyDynamics::CalcContactSystemVariables(), ConstraintSet::force, ConstraintSet::G, ConstraintSet::gamma, ConstraintSet::GT_qr, ConstraintSet::GT_qr_Q, ConstraintSet::H, ConstraintSet::linear_solver, LOG, ConstraintSet::qddot_y, ConstraintSet::qddot_z, RigidBodyDynamics::SolveContactSystemNullSpace(), ConstraintSet::Y, and ConstraintSet::Z.
RBDL_DLLAPI void ForwardDynamicsContactsRangeSpaceSparse (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, const Math::VectorNd & Tau, ConstraintSet & CS, Math::VectorNd & QDDot)
Definition at line 414 of file Contacts.cc.
References ConstraintSet::a, ConstraintSet::C, RigidBodyDynamics::CalcContactSystemVariables(), ConstraintSet::force, ConstraintSet::G, ConstraintSet::gamma, ConstraintSet::H, ConstraintSet::K, ConstraintSet::linear_solver, and RigidBodyDynamics::SolveContactSystemRangeSpaceSparse().
RBDL_DLLAPI void SolveContactSystemDirect (Math::MatrixNd & H, const Math::MatrixNd & G, const Math::VectorNd & c, const Math::VectorNd & gamma, Math::VectorNd & qddot, Math::VectorNd & lambda, Math::MatrixNd & A, Math::VectorNd & b, Math::VectorNd & x, Math::LinearSolver & linear_solver)
Solves the full contact system directly, i.e. simultaneously for contact forces and joint accelerations.
This solves a linear system.
Parameters
H the joint space inertia matrix
G the constraint jacobian
c the vector of the upper part of the right hand side of the system
gamma the vector of the lower part of the right hand side of the system
qddot result: joint accelerations
lambda result: constraint forces
A work-space for the matrix of the linear system
b work-space for the right-hand-side of the linear system
x work-space for the solution of the linear system
type of solver that should be used to solve the system
Definition at line 161 of file Contacts.cc.
References LinearSolverColPivHouseholderQR, LinearSolverHouseholderQR, LinearSolverPartialPivLU, and LOG.
RBDL_DLLAPI void SolveContactSystemNullSpace (Math::MatrixNd & H, const Math::MatrixNd & G, const Math::VectorNd & c, const Math::VectorNd & gamma, Math::VectorNd & qddot, Math::VectorNd & lambda, Math::MatrixNd & Y, Math::MatrixNd & Z, Math::VectorNd & qddot_y, Math::VectorNd & qddot_z, Math::LinearSolver & linear_solver)
Solves the contact system by first solving for the joint accelerations and then for the constraint forces.
This methods requires a matrix of the form with the property that can be computed using a QR decomposition (e.g. see code for ForwardDynamicsContactsNullSpace()).
Parameters
H the joint space inertia matrix
G the constraint jacobian
c the vector of the upper part of the right hand side of the system
gamma the vector of the lower part of the right hand side of the system
qddot result: joint accelerations
lambda result: constraint forces
Y basis for the range-space of the constraints
Z basis for the null-space of the constraints
qddot_y work-space of size
qddot_z work-space of size
linear_solver type of solver that should be used to solve the system
Definition at line 248 of file Contacts.cc.
References LinearSolverColPivHouseholderQR, LinearSolverHouseholderQR, LinearSolverPartialPivLU, and LOG.
RBDL_DLLAPI void SolveContactSystemRangeSpaceSparse (Model & model, Math::MatrixNd & H, const Math::MatrixNd & G, const Math::VectorNd & c, const Math::VectorNd & gamma, Math::VectorNd & qddot, Math::VectorNd & lambda, Math::MatrixNd & K, Math::VectorNd & a, Math::LinearSolver linear_solver)
Solves the contact system by first solving for the the joint accelerations and then the contact forces using a sparse matrix decomposition of the joint space inertia matrix.
This method exploits the branch-induced sparsity by the structure preserving decomposition described in RBDL, Section 6.5.
Parameters
H the joint space inertia matrix
G the constraint jacobian
c the vector of the upper part of the right hand side of the system
gamma the vector of the lower part of the right hand side of the system
qddot result: joint accelerations
lambda result: constraint forces
K work-space for the matrix of the constraint force linear system
a work-space for the right-hand-side of the constraint force linear system
linear_solver type of solver that should be used to solve the constraint force system
Definition at line 211 of file Contacts.cc.
References RigidBodyDynamics::Math::SparseFactorizeLTL(), RigidBodyDynamics::Math::SparseSolveLTx(), and RigidBodyDynamics::Math::SparseSolveLx().